# Generated by Django 5.2.9 on 2026-01-21 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naklad_szt', models.PositiveIntegerField(default=1, help_text='Dodatnia liczba całkowita', validators=[django.core.validators.MinValueValidator(1)])),
                ('objetosc_m3', models.FloatField(default=0)),
                ('konstrukcja_kg', models.FloatField(default=0)),
                ('sklejka_m3', models.FloatField(default=0)),
                ('drewno_m3', models.FloatField(default=0)),
                ('plyta_m2', models.FloatField(default=0)),
                ('druk_m2', models.FloatField(default=0)),
                ('led_mb', models.FloatField(default=0)),
                ('tworzywa_m2', models.FloatField(default=0)),
                ('koszty_pozostale', models.FloatField(default=0)),
                ('stopien_skomplikowania', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rodzaj_tworzywa', models.CharField(blank=True, choices=[('HIPS', 'HIPS'), ('PMMA', 'PMMA'), ('PET', 'PET'), ('PC', 'PC'), ('ABS', 'ABS'), ('NAKLEJKA', 'NAKLEJKA'), ('GUMA', 'GUMA'), ('TKANINA', 'TKANINA')], max_length=50, null=True)),
                ('rodzaj_displaya', models.CharField(choices=[('ekspozytor_tworzywowy', 'Ekspozytor tworzywowy'), ('naladowy', 'Display naladowy'), ('potykacz', 'Potykacz'), ('regal', 'Regał QPD/HPD/PD'), ('paleciak', 'Paleciak QPD/HPD/PD'), ('owijka', 'Owijka paletowa'), ('kaseton', 'Kaseton'), ('wyspa', 'Wyspa'), ('druciak', 'Druciak'), ('pozostale', 'Pozostałe')], default='ekspozytor_pmma', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.FloatField()),
                ('user_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimations.estimationinput')),
            ],
        ),
    ]
