# Generated by Django 5.2.9 on 2025-12-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naklad_szt', models.FloatField()),
                ('objetosc_m3', models.FloatField()),
                ('konstrukcja_kg', models.FloatField()),
                ('sklejka_m3', models.FloatField()),
                ('drewno_m3', models.FloatField()),
                ('plyta_m2', models.FloatField()),
                ('druk_m2', models.FloatField()),
                ('led_mb', models.FloatField()),
                ('tworzywa_m2', models.FloatField()),
                ('koszty_pozostale', models.FloatField()),
                ('stopien_skomplikowania', models.IntegerField()),
                ('rodzaj_tworzywa', models.CharField(choices=[('HIPS', 'HIPS'), ('PMMA', 'PMMA'), ('PET', 'PET'), ('PC', 'PC'), ('ABS', 'ABS'), ('NAKLEJKA', 'NAKLEJKA'), ('GUMA', 'GUMA'), ('TKANINA', 'TKANINA')], max_length=50)),
                ('rodzaj_displaya', models.CharField(choices=[('ekspozytor_pmma', 'Ekspozytor PMMA'), ('ekspozytor_tworzywowy', 'Ekspozytor tworzywowy'), ('maly_naladowy', 'Mały display naladowy'), ('potykacz', 'Potykacz'), ('regal_qpd', 'Regal QPD'), ('regal_hpd', 'Regal HPD'), ('regal_pd', 'Regal PD'), ('paleciak_qpd', 'Paleciak QPD'), ('paleciak_hpd', 'Paleciak HPD'), ('paleciak_pd', 'Paleciak PD'), ('owijka_pd', 'Owijka paletowa'), ('kaseton', 'Kaseton'), ('wyspa', 'Wyspa'), ('druciak', 'Druciak'), ('pozostale', 'Pozostałe')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstimationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.FloatField()),
                ('user_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimations.estimationinput')),
            ],
        ),
    ]
