# Generated by Django 5.2.9 on 2025-12-13 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('shelves', models.IntegerField()),
                ('material_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='EstimationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.FloatField()),
                ('user_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimations.estimationinput')),
            ],
        ),
    ]
