# Generated by Django 5.2.9 on 2026-01-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationinput',
            name='rodzaj_tworzywa',
            field=models.CharField(blank=True, choices=[('HIPS', 'HIPS'), ('PMMA', 'PMMA'), ('PET', 'PET'), ('PC', 'PC'), ('ABS', 'ABS'), ('NAKLEJKA', 'NAKLEJKA'), ('GUMA', 'GUMA'), ('TKANINA', 'TKANINA'), ('DISPA', 'DISPA'), ('KARTON', 'KARTON')], max_length=50, null=True),
        ),
    ]
