# Generated by Django 5.2.9 on 2026-01-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.FloatField()),
                ('user_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimations.estimationinput')),
            ],
        ),
    ]
